---
# Update package list, install Python and pip, and install required packages

# Update the package list on the system
- name: Update package list
  apt:
    update_cache: yes

# Install Python and pip, as well as the Python virtual environment package
- name: Install Python and pip
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: latest

# Install required Python packages using pip
- name: Install required packages
  pip:
    name: "{{ item }}"
  # List the required Python packages to be installed
  with_items:
    - Django
    - gunicorn
    - psycopg2-binary
    - django_extensions
