---
- name: Clone repository
  git:
    repo: "{{ app_repo }}"
    dest: "{{ app_path }}"
    clone: yes
    update: yes
    force: yes

- name: Create virtual environment
  command: python3 -m venv "{{ virtualenv_path }}"
  args:
    creates: "{{ virtualenv_path }}"

- name: Make and run database migrations
  command: python3 {{ app_path }}/manage.py migrate
  environment:
    DJANGO_SETTINGS_MODULE: "{{ app_name }}.settings"   